export const photos = [
	{
		image: '12764693_10156449519320062_5047064385309877561_o.jpg',
		title: 'Untitled',
		date_created: '2019',
		description: 'Acrylic on canvas',
	},
	{
		image: 'bloodmandala1_2014.jpg',
		title: 'Blood Mandala: Portrait of a 37 year-old First Nations, HIV positive, gay male drag queen',
		date_created: '2014',
		description: 'Silkscreened blood with translucent base on canvas',
	},
	{
		image: 'bloodmandala2_2014.jpg',
		title: 'Blood Mandala: Portrait of a 25 year-old half Chinese female heroin addict with Hepatitis C',
		date_created: '2014',
		description: 'Silkscreened blood with translucent base on canvas',
	},
	{
		image: 'coatinglanguage_2015.jpg',
		title: 'Coding Language',
		date_created: '2013',
		description: 'Acrylic and plaster on canvas',
	},
	{
		image: 'Dispilio_2015.jpg',
		title: 'Dispilio Revealed',
		date_created: '2015',
		description: 'Acrylic on canvas',
	},
	{
		image: 'divergent_2015.jpg',
		title: 'Divergent [SOLD]',
		date_created: '2017',
		description: 'Acrylic on canvas',
	},
	{
		image: 'glam_2015.jpg',
		title: 'Glam Rock',
		date_created: '2016',
		description: 'Acrylic on canvas',
	},
	{
		image: 'IMG_0178.jpg',
		title: 'The Grand Maraschino [SOLD]',
		date_created: '2014',
		description: 'Acrylic on canvas',
	},
	{
		image: 'IMG_0208.jpg',
		title: 'Pages',
		date_created: '2018',
		description: 'Acrylic on panel board',
	},
	{
		image: 'IMG_0360.jpg',
		title: 'Natures First Green Is Gold',
		date_created: '2022',
		description: 'Acrylic on canvas',
	},
	{
		image: 'IMG_0410.jpg',
		title: 'Untitled',
		date_created: '2013',
		description: 'Acrylic on canvas',
	},
	{
		image: 'IMG_0411.jpg',
		title: 'Love Actually',
		date_created: '2022',
		description: 'Acrylic on canvas',
	},
	{
		image: 'IMG_0412.jpg',
		title: 'Monsters In The Attic',
		date_created: '2019',
		description: 'Acrylic on canvas',
	},
	{
		image: 'IMG_0413.jpg',
		title: 'Snail Tail',
		date_created: '2021',
		description: 'Acrylic on canvas',
	},
	{
		image: 'IMG_0776.jpg',
		title: 'Pollywog [SOLD]',
		date_created: '2019',
		description: 'Acrylic on canvas',
	},
	{
		image: 'IMG_2188.jpg',
		title: 'Untitled [SOLD]',
		date_created: '2017',
		description: 'Acrylic on panel board',
	},
	{
		image: 'intersectingpop_2015.jpg',
		title: 'Intersecting Pop [SOLD]',
		date_created: '2017',
		description: 'Acrylic on panel board',
	},
	{
		image: 'lunarcircus_2014.jpg',
		title: 'Lunarcircus',
		date_created: '2019',
		description: 'Acrylic on canvas',
	},
	{
		image: 'MandalaA_2014.jpg',
		title: 'Mandala A',
		date_created: '2013',
		description: 'Silkscreen ink on canvas',
	},
	{
		image: 'mandalaB_2014.jpg',
		title: 'Mandala B',
		date_created: '2013',
		description: 'Silkscreen ink on canvas',
	},
	{
		image: 'patrik_2014.jpg',
		title: 'Patrik',
		date_created: '2013',
		description: 'Acrylic on panel board',
	},
	{
		image: 'spaces1_2015.jpg',
		title: 'Spaces',
		date_created: '2017',
		description: 'Acrylic on panel board',
	},
	{
		image: 'tetrix_2014.jpg',
		title: 'Tetrix',
		date_created: '2012',
		description: 'Acrylic on panel board',
	},
	{
		image: 'TOE_2015.jpg',
		title: 'T.O.E.',
		date_created: '2015',
		description: 'Acrylic on canvas',
	},
	{
		image: 'trans_2014.jpg',
		title: 'Trans',
		date_created: '2013',
		description: 'Acrylic on panel board',
	},
	{
		image: 'underwater_2015.jpg',
		title: 'Underwater City',
		date_created: '2020',
		description: 'Acrylic on canvas',
	},
];
