export const photos = [
	{
		image: '12764693_10156449519320062_5047064385309877561_o.jpg',
		title: 'Photo 1',
		date_created: '2018-12-01',
		description: ' as;dkjf;aksdj k;lajsd;f lkjsad;lkf j ;jasd;lkfl ksdl;kfj; lkja;lskdjf l;k jl;kasjd fl;kj lk;sjd f;kljsad f;lkj ;lkjs a;dlkfjal;skdjf;lkasjdf;lk asdf;klja j;lks djfl;k sdjflk ',
	},
	{
		image: 'bloodmandala1_2014.jpg',
		title: '',
		date_created: '',
		description: '',
	},
	{
		image: 'bloodmandala2_2014.jpg',
		title: '',
		date_created: '',
		description: '',
	},
	{
		image: 'coatinglanguage_2015.jpg',
		title: '',
		date_created: '',
		description: '',
	},
	{
		image: 'Dispilio_2015.jpg',
		title: '',
		date_created: '',
		description: '',
	},
	{
		image: 'divergent_2015.jpg',
		title: '',
		date_created: '',
		description: '',
	},
	{
		image: 'glam_2015.jpg',
		title: '',
		date_created: '',
		description: '',
	},
	{
		image: 'IMG_0178.jpg',
		title: '',
		date_created: '',
		description: '',
	},
	{
		image: 'IMG_0208.jpg',
		title: '',
		date_created: '',
		description: '',
	},
	{
		image: 'IMG_0360.jpg',
		title: '',
		date_created: '',
		description: '',
	},
	{
		image: 'IMG_0410.jpg',
		title: '',
		date_created: '',
		description: '',
	},
	{
		image: 'IMG_0411.jpg',
		title: '',
		date_created: '',
		description: '',
	},
	{
		image: 'IMG_0412.jpg',
		title: '',
		date_created: '',
		description: '',
	},
	{
		image: 'IMG_0413.jpg',
		title: '',
		date_created: '',
		description: '',
	},
	{
		image: 'IMG_0776.jpg',
		title: '',
		date_created: '',
		description: '',
	},
	{
		image: 'IMG_2188.jpg',
		title: '',
		date_created: '',
		description: '',
	},
	{
		image: 'intersectingpop_2015.jpg',
		title: '',
		date_created: '',
		description: '',
	},
	{
		image: 'lunarcircus_2014.jpg',
		title: '',
		date_created: '',
		description: '',
	},
	{
		image: 'MandalaA_2014.jpg',
		title: '',
		date_created: '',
		description: '',
	},
	{
		image: 'mandalaB_2014.jpg',
		title: '',
		date_created: '',
		description: '',
	},
	{
		image: 'patrik_2014.jpg',
		title: '',
		date_created: '',
		description: '',
	},
	{
		image: 'spaces1_2015.jpg',
		title: '',
		date_created: '',
		description: '',
	},
	{
		image: 'tetrix_2014.jpg',
		title: '',
		date_created: '',
		description: '',
	},
	{
		image: 'TOE_2015.jpg',
		title: '',
		date_created: '',
		description: '',
	},
	{
		image: 'trans_2014.jpg',
		title: '',
		date_created: '',
		description: '',
	},
	{
		image: 'underwater_2015.jpg',
		title: '',
		date_created: '',
		description: '',
	},
];
